---
- hosts: all
  user: ansible
  become: True
  tasks:
    - name: Install stuff
      apt:
        name: '{{ item }}'
        state: present
        update_cache: True
      loop:
        - zsh
        - vim
        - curl
        - unzip
        - wget
        - apt-transport-https
        - ca-certificates
        - gnupg
        - lynx
        - tmux
        - make
        - tree
        - speedtest-cli
        - glances
        - virtualbox-qt
        - qemu-kvm
        - libvirt-daemon-system
        - libvirt-clients
        - bridge-utils
        - virtinst
        - virt-manager
        - resolvconf