---
- hosts: all
  user: jharter1
  become: True
  tasks:
    - name: Install stuff
      apt:
        name: '{{ item }}'
        state: present
        update_cache: True
      loop:
        - zsh
        - aptitude
        - vim
        - curl
        - unzip
        - wget
        - apt-transport-https
        - ca-certificates
        - gnupg
        - lynx
        - tmux
        - make
        - tree
        - speedtest-cli
        - glances
        - bridge-utils
        - resolvconf
        - googler
        - ranger
        - calcurse
        - neofetch
        - chkrootkit
        - iputils-ping
        - iputils-tracepath
        - locate
        - logwatch
        - fail2ban
        - htop
        - qemu-utils
